const express = require("express")
const router = express.Router()

const userController = require("../controller/userController")
const { checkToken,checkUserToken,checkSuperAdminToken,checkApiKey} = require("../middleware/checkToken")

router.post("/sign_up", userController.singUp)
router.post("/add_user",checkToken,userController.createUser)
router.get("/users",checkToken,userController.getUsers)
router.get("/admins",checkToken,userController.getAdmins)
router.get("/user",checkToken,userController.getUser)
router.post("/update_user",checkToken,userController.updateUser)
router.post("/delete_multiple_user",checkToken,userController.deleteMultipleUser)
router.post("/login",userController.login)
router.post("/verify_user",checkApiKey,userController.verifyUser)
router.post("/reset_password_token",userController.resetPasswordToken)
router.post("/verify_token",userController.verifyToken)
router.post("/update_reset_password",userController.updateResetPassword)
router.post("/redeem_code",checkUserToken,userController.redeemCode)
router.post("/merge_selected_user",userController.mergeSelectedUser)
router.post("/users_data_by_id",userController.usersDataById)
router.post("/deprecate_user_product",checkToken,userController.deprecateProduct)
router.post("/generate_apikey",checkSuperAdminToken,userController.makeSecretKey)
router.post("/delete_apikey",checkSuperAdminToken,userController.deleteSecretKey)
router.get("/get_apikeys",checkSuperAdminToken,userController.getSecretKeys)
router.post("/toggle_subs_visibility",checkToken,userController.toggleSubsVisibility)
router.post("/send_password_reset_email",checkApiKey,userController.sendPasswordResetEmail)

module.exports = router
